<?php


// all functional functions are moved to modules/custom_hooks

function advalvas_preprocess_node(&$variables) {
	//$nid = $variables['node']->nid->value;
  //$num_comment = db_query('SELECT comment_count FROM {comment_entity_statistics} WHERE entity_id = ' . $nid)->fetchAssoc();
  //kint($num_comment);
  //$variables['comment_count'] = $num_comment['comment_count'];
  //$variables['comment_count'] = $variables['node']->get('YOUR_COMMENT_FIELD')->comment_count;
}